In [1]:
print("hello wolrd")

hello wolrd


In [5]:
a = 10

In [6]:
# Numpy : numarical python.

In [7]:
# array

# list 

In [8]:
# lst = [12, 10, "hlo", 10.8, True, 100]

In [10]:
# array : 

In [11]:
# 2005 -> trevius olephint

In [12]:
!pip install numpy

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [ ]:
# objects:

In [ ]:
ndarray : when we create an object with the help of array method. we call that object is ndarray.

In [14]:
import numpy as xyz

In [15]:
arr = xyz.array(20)

In [16]:
arr

array(20)

In [17]:
type(arr)

numpy.ndarray

In [20]:
# to check ndarray demessions:

# attribute ==> ndim

# ndim attribue

In [21]:
import numpy as np

In [22]:
arrx = np.array(100)

In [23]:
arrx.ndim

0

In [25]:
arr1 = np.array([12, 10, 45, 10, 78])

In [26]:
arr1

array([12, 10, 45, 10, 78])

In [27]:
type(arr1)

numpy.ndarray

In [28]:
arr1.ndim

1

In [35]:
arr3 = np.array([[12, 34, 56, 34, 100], [34, 56, 45, 67, 45]])

In [32]:
arr3.ndim

2

In [33]:
arr3

array([[ 12,  34,  56,  34, 100],
       [ 34,  56,  45,  67,  45]])

In [40]:
arr4 = np.array([[[12, 45, 23], [45, 34, 56], [45, 34, 56]], [[23, 56, 34], [56, 56, 34], [90, 56, 34]]])

In [41]:
arr4

array([[[12, 45, 23],
        [45, 34, 56],
        [45, 34, 56]],

       [[23, 56, 34],
        [56, 56, 34],
        [90, 56, 34]]])

In [42]:
arr4.ndim

3

In [44]:
# shape

In [45]:
arr1 = np.array([12, 10, 45, 10, 78])

In [46]:
arr1.ndim

1

In [47]:
arr1.shape

(5,)

In [48]:
arr3 = np.array([[12, 34, 56, 34, 100], [34, 56, 45, 67, 45]])

In [49]:
arr3.ndim

2

In [50]:
arr3.shape

(2, 5)

In [51]:
arr3

array([[ 12,  34,  56,  34, 100],
       [ 34,  56,  45,  67,  45]])

In [56]:
# arr4 = np.array([[[12, 45, 23], [45, 34, 56], [45, 34, 56]], [[23, 56, 34], [56, 56, 34], [90, 56, 34]]])

arr4 = np.array([[[12, 45, 23], [45, 34, 56]], [[23, 56, 34], [90, 56, 34]]])

In [57]:
arr4.ndim

3

In [58]:
arr4.shape

(2, 2, 3)

In [59]:
arr4

array([[[12, 45, 23],
        [45, 34, 56]],

       [[23, 56, 34],
        [90, 56, 34]]])

In [60]:
# indexing or slicing.

In [61]:
arr1 = np.array([12, 10, 45, 10, 78])

In [62]:
arr1

array([12, 10, 45, 10, 78])

In [63]:
arr1[3]

10

In [64]:
arr1[::-1]

array([78, 10, 45, 10, 12])

In [65]:
arr3 = np.array([[12, 34, 56, 34, 100], [34, 56, 45, 67, 45]])

In [67]:
arr3[1][3]

67