In [1]:
import numpy as np

In [8]:
arr = np.array([[[12, 23, 10, 45], [56, 34, 23, 64]], [[56, 34, 23, 6], [67, 34, 23, 12]]])

In [9]:
arr

array([[[12, 23, 10, 45],
        [56, 34, 23, 64]],

       [[56, 34, 23,  6],
        [67, 34, 23, 12]]])

In [10]:
arr.ndim

3

In [13]:
arr[1][1][1 : 3]

array([34, 23])

In [ ]:
joning two ndarray

In [14]:
arr1 = np.array([12, 45, 3, 100])

In [15]:
arr2 = np.array([45, 6, 3, 2])

In [16]:
zx = arr1 + arr2

In [17]:
zx

array([ 57,  51,   6, 102])

In [ ]:
conctaenate

In [18]:
import numpy as np

In [20]:
qw = np.concatenate((arr1, arr2))

In [21]:
qw

array([ 12,  45,   3, 100,  45,   6,   3,   2])

In [30]:
arr1 = np.array([12, 45, 3, 100])
arr2 = np.array([45, 6, 3, 2])
arr3 = np.array([45, 34, 21, 45])

In [35]:
we = np.stack((arr1, arr2, arr3), axis = 0, )

In [36]:
we

array([[ 12,  45,   3, 100],
       [ 45,   6,   3,   2],
       [ 45,  34,  21,  45]])

In [37]:
zx = np.array([45, 23, 45, 23, 12, 67, 34, 2])

In [38]:
# where

np.where(zx == 67)

(array([5], dtype=int64),)

In [40]:
zx = np.array([45, 23, 45, 23, 12, 67, 34, 2, 67, 23, 23, 12, 67])

In [41]:
np.where(zx == 67)

(array([ 5,  8, 12], dtype=int64),)

In [42]:
zx = np.array([45, 23, 45, 23, 12, 67, 34, 2, 67, 23, 23, 12, 67])

In [46]:
np.array_split(zx, 4)

[array([45, 23, 45, 23]),
 array([12, 67, 34]),
 array([ 2, 67, 23]),
 array([23, 12, 67])]

In [47]:
# reshape()

In [48]:
zx = np.array([45, 23, 45, 23, 12, 67, 34, 2, 67, 23, 23, 12, 67])

In [49]:
np.sort(zx)

array([ 2, 12, 12, 23, 23, 23, 23, 34, 45, 45, 67, 67, 67])

In [ ]:
np.append

In [50]:
help(np.append)

Help on _ArrayFunctionDispatcher in module numpy:

append(arr, values, axis=None)
    Append values to the end of an array.

    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.

    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.

    See Also
    --------
    insert : Insert elements into an array.
    delete : Delete e