In [1]:
import numpy as np

In [ ]:
# 1 --- 40

30

In [2]:
from numpy import random

In [4]:
x = random.randint(40, size = (30))

In [6]:
y = random.randint(40, size = (30))

In [7]:
x

array([39, 34, 15,  9, 16, 15, 37, 12,  1, 39, 31, 15, 12, 39, 24, 25,  0,
       25, 32, 21,  4,  5, 39, 11,  2,  7, 39, 21, 20, 25])

In [8]:
y

array([25, 22, 14,  9, 39, 19, 30,  8, 19, 33, 28, 35, 13, 18,  5,  4, 20,
       31, 24, 22,  6, 22, 31,  4, 35,  8,  4,  3, 16, 16])

In [9]:
import pandas as pd

In [11]:
# zx = pd.DataFrame(dict(x))

In [13]:
data = pd.DataFrame({"x" : x, "y" : y})

In [14]:
data

x   y
0   39  25
1   34  22
2   15  14
3    9   9
4   16  39
5   15  19
6   37  30
7   12   8
8    1  19
9   39  33
10  31  28
11  15  35
12  12  13
13  39  18
14  24   5
15  25   4
16   0  20
17  25  31
18  32  24
19  21  22
20   4   6
21   5  22
22  39  31
23  11   4
24   2  35
25   7   8
26  39   4
27  21   3
28  20  16
29  25  16

In [57]:
class train_test_and_split_now:
    def __init__(self, x, y, test_size):
        self.x = x
        self.y = y
        self.test_size = test_size

    def train_test_devider(self):
        ind = len(self.x)

        index = np.arange(ind)
        random.shuffle(index)
        # print(index)

        index_slice = int(len(xyz) * self.test_size)

        train_indexes = index[index_slice : ]
        test_indexes = index[ : index_slice]

        x_train = x[train_indexes]
        x_test = x[test_indexes]

        y_train = y[train_indexes]
        y_test = y[test_indexes]

        return x_train, x_test, y_train, y_test
        
        
        

In [63]:
obj = train_test_and_split_now(x, y, 0.5)

In [64]:
x_train, x_test, y_train, y_test = obj.train_test_devider()

x_train.shape

(22,)

In [65]:
x_test.shape

(8,)

In [18]:
xyz = np.array([12, 34, 56, 78, 56, 45, 67, 45, 34, 567, 34, 34, 23, 56, 34, 56])

In [19]:
len(xyz)

16

In [20]:
# 0.5   -> 5 / 10

In [22]:
print(len(xyz) * 0.5)

8.0


In [23]:
xyz[ : 8]

array([12, 34, 56, 78, 56, 45, 67, 45])

In [24]:
xyz[ 8 : ]

array([ 34, 567,  34,  34,  23,  56,  34,  56])