In [2]:
# Numpy :

In [3]:
# ndarray : 

In [4]:
import numpy as np

In [5]:
arr = np.array([[12, 10, 50, 100], [45, 34, 67, 34]])

In [6]:
arr

array([[ 12,  10,  50, 100],
       [ 45,  34,  67,  34]])

In [7]:
arr.ndim

2

In [8]:
arr.shape

(2, 4)

## list => indexing, slicing

In [9]:
arr1 = np.array([12, 20, 34, 23, 45, 56, 34, 23, 100])

In [10]:
arr1

array([ 12,  20,  34,  23,  45,  56,  34,  23, 100])

In [11]:
arr1.ndim

1

In [13]:
arr1[4]

45

In [ ]:
# slcing:, =>    objname[start : end : increment]

# defaut values:
#     start => 0
#     end = n - 1
#     increment = 1

In [14]:
arr1 = np.array([12, 20, 34, 23, 45, 56, 34, 23, 100])

In [17]:
arr1[2 : 7 : 1]

array([34, 23, 45, 56, 34])

In [18]:
arr1[3 : ]

array([ 23,  45,  56,  34,  23, 100])

In [19]:
arr1[ : 5]

array([12, 20, 34, 23, 45])

In [20]:
arr1[: : -1]

array([100,  23,  34,  56,  45,  23,  34,  20,  12])

In [21]:
arr1 = np.array([12, 20, 34, 23, 45, 56, 34, 23, 100])

In [24]:
arr1[ : : 2]

array([ 12,  34,  45,  34, 100])

## with 2d

In [26]:
arr = np.array([[12, 10, 50, 100], [45, 34, 67, 34]])

In [27]:
arr

array([[ 12,  10,  50, 100],
       [ 45,  34,  67,  34]])

In [29]:
arr[1][2]

67

In [30]:
arr[0][2]

50

In [32]:
arr[1][1 : ]

array([34, 67, 34])

In [33]:
xyz = np.array([[12, 34, 23, 45, 23, 12], [45, 67, 45, 34, 45, 2], [78, 56, 45, 23, 45, 23]])

In [34]:
xyz.ndim

2

In [35]:
xyz[2][1 : 5]

array([56, 45, 23, 45])

## with 3d

In [36]:
arr = np.array([[[12, 10, 50, 100], [45, 34, 67, 34]], [[56, 45, 34, 44], [67, 45, 34, 23]]])

In [37]:
arr.ndim

3

In [38]:
arr

array([[[ 12,  10,  50, 100],
        [ 45,  34,  67,  34]],

       [[ 56,  45,  34,  44],
        [ 67,  45,  34,  23]]])

In [39]:
arr[2][2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [40]:
arr[1][0][3]

44

In [41]:
arr[1][1]

array([67, 45, 34, 23])

In [42]:
arr[0][7]

IndexError: index 7 is out of bounds for axis 0 with size 2

In [43]:
arr[0][1][3]

34

In [44]:
arr = np.array([[[12, 10, 50, 100], [45, 34, 67, 34]], [[56, 45, 34, 44], [67, 45, 34, 23]]])

In [47]:
arr[1][0][1]

45

## where()

In [50]:
xyz = np.array([12, 20, 56, 34, 23, 45, 56, 34, 23, 100, 56])

In [51]:
np.where(xyz == 56)

(array([ 2,  6, 10], dtype=int64),)

## sort()

In [52]:
xyz = np.array([12, 20, 56, 34, 23, 45, 56, 34, 23, 100, 56])

In [53]:
np.sort(xyz)

array([ 12,  20,  23,  23,  34,  34,  45,  56,  56,  56, 100])

In [54]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warning sections 