In [1]:
# [0, 00, 000, 00, 0]

In [16]:
lst = []

In [17]:
for i in range(1, 6):
    lst.append(i * "0")

In [18]:
lst

['0', '00', '000', '0000', '00000']

In [19]:
zx = lst[ : 4]

In [20]:
zx

['0', '00', '000', '0000']

In [21]:
pq = zx[: : -1]

In [22]:
pq

['0000', '000', '00', '0']

In [9]:
# extend()

In [23]:
lst.extend(pq)

In [24]:
lst

['0', '00', '000', '0000', '00000', '0000', '000', '00', '0']

In [14]:
lst = [12, 34, 23, 45, 10]

pp = [23, 45, 23, 100]

In [15]:
lst + pp

[12, 34, 23, 45, 10, 23, 45, 23, 100]

In [12]:
lst.extend(pp)

In [13]:
lst

[12, 34, 23, 45, 10, 23, 45, 23, 100]

In [ ]:
# trim_zero()

In [25]:
import numpy as np

In [29]:
zx = np.array([0, 8, 5, 5, 0, 7, 3, 0, 0, 0])

In [30]:
np.trim_zeros(zx)

array([8, 5, 5, 0, 7, 3])

In [31]:
# unique()

In [32]:
a = np.array([1, 5, 3, 1, 2, 3, 1, 2, 1, 1, 1, 7, 5, 8, 3, 7, 1, 10])

In [33]:
np.unique(a)

array([ 1,  2,  3,  5,  7,  8, 10])

In [34]:
# np.arange()

In [35]:
# arange(start, end, increment)

In [38]:
zx = np.arange(1, 21, 2)

In [39]:
zx

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
# range(1, 20)

In [42]:
# random

In [44]:
from numpy import random
# import random

In [54]:
arr = random.randint(100, size = (5, 6, 3))
arr

array([[[33, 32, 98],
        [75, 42, 54],
        [84, 56, 48],
        [69,  3, 52],
        [46, 62, 90],
        [35, 60, 65]],

       [[71,  9, 45],
        [59, 60, 90],
        [ 7, 41, 55],
        [ 4, 85, 30],
        [ 9, 38, 57],
        [ 7, 19, 30]],

       [[20, 44, 57],
        [37, 67, 34],
        [72, 65, 70],
        [18, 54, 24],
        [82, 70, 97],
        [59, 43, 71]],

       [[43, 63, 30],
        [81, 54, 54],
        [22, 94, 53],
        [55, 55, 35],
        [36, 30, 70],
        [63, 59, 77]],

       [[16, 35, 47],
        [87, 64, 42],
        [54,  5, 69],
        [34, 27,  5],
        [88, 22, 86],
        [ 6, 15, 96]]])

In [55]:
arr = random.randint(100, size = (5, 4))
arr

array([[57, 37, 41, 27],
       [48, 87, 17, 73],
       [ 4, 86, 65, 38],
       [58, 60, 78, 42],
       [36, 71, 79,  0]])

In [56]:
# rand()  -> 0 - 1

In [65]:
xyz = random.rand(3, 2)
xyz

array([[0.26118469, 0.99530745],
       [0.12124327, 0.05221489],
       [0.93969336, 0.3302264 ]])

In [66]:
# choice()

In [77]:
ch = random.choice([1, 2, 3, 4, 5, 6])

In [78]:
ch

5

In [81]:
ch = random.choice([1, 2, 3, 4, 5, 6], size = (5, 3))

In [82]:
ch

array([[1, 4, 2],
       [5, 5, 4],
       [6, 2, 1],
       [6, 4, 6],
       [5, 5, 6]])

In [84]:
# shuffle()

In [90]:
ca = np.array([1, 2, 3, 4, 5, 6, 10])

In [91]:
ca

array([ 1,  2,  3,  4,  5,  6, 10])

In [92]:
random.shuffle(ca)

In [93]:
ca

array([ 6,  5,  4, 10,  3,  2,  1])

In [ ]:
trim_zero()
unique()
arange()
random
randint
rand
choice
shuffle

In [96]:
zx = np.array([ 1,  2,  3,  4,  5,  6, 1, 1, 2, 5, 2, 10])

In [97]:
np.unique(zx)

array([ 1,  2,  3,  4,  5,  6, 10])

In [98]:
help(np.copyto)

Help on _ArrayFunctionDispatcher in module numpy:

copyto(...)
    copyto(dst, src, casting='same_kind', where=True)

    Copies values from one array to another, broadcasting as necessary.

    Raises a TypeError if the `casting` rule is violated, and if
    `where` is provided, it selects which elements to copy.

    .. versionadded:: 1.7.0

    Parameters
    ----------
    dst : ndarray
        The array into which values are copied.
    src : array_like
        The array from which values are copied.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur when copying.

          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are allowed.
          * 'safe' means only casts which can preserve values are allowed.
          * 'same_kind' means only safe casts or casts within a kind,
            like float64 to float32, are allowed.
          * 'unsafe' means 