In [1]:
import numpy as np

In [3]:
zx = np.array([[12, 34, 56, 34, 23, 100], [45, 45, 100, 67, 34, 10]])

In [4]:
zx.ndim

2

In [5]:
zx

array([[ 12,  34,  56,  34,  23, 100],
       [ 45,  45, 100,  67,  34,  10]])

In [6]:
zx = np.array([12, 34, 56, 34, 23, 100, 45, 45, 100, 67, 34, 10])

In [7]:
zx[-5]

45

# fancy indexing in numpy:

In [ ]:
boolean indexing.

In [8]:
zx = np.array([12, 34, 56, 34, 23, 100, 45, 45, 100, 67, 34, 10])

In [11]:
qw = zx < 50

In [12]:
qw

array([ True,  True, False,  True,  True, False,  True,  True, False,
       False,  True,  True])

In [13]:
zx[qw]

array([12, 34, 34, 23, 45, 45, 34, 10])

In [14]:
my2d = np.array([[12, 34, 56, 34, 23, 100], [45, 45, 100, 67, 34, 10]])

In [17]:
k = my2d >= 40

In [18]:
my2d[k]

array([ 56, 100,  45,  45, 100,  67])

In [19]:
# zeros()

In [21]:
xyz = np.zeros((3, 3))

In [23]:
xyz

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
yu = np.ones((5, 3))

In [29]:
yu

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# eye()

In [32]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [34]:
my2d = np.array([[12, 34, 56, 34, 23, 100], [45, 45, 100, 67, 34, 10]])

In [35]:
my2d

array([[ 12,  34,  56,  34,  23, 100],
       [ 45,  45, 100,  67,  34,  10]])

In [36]:
trans = np.transpose(my2d)

In [37]:
trans

array([[ 12,  45],
       [ 34,  45],
       [ 56, 100],
       [ 34,  67],
       [ 23,  34],
       [100,  10]])

In [38]:
# linspace()

In [41]:
er = np.linspace(0, 3, 7)

In [42]:
er

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [43]:
# Data Types:
#     string ---> U1
#     integer -----> int1
#                     int 2
#                     int4 ( -238 to 238 )
#     float -----> _float

In [44]:
# type()



In [45]:
zx = np.array([12, 34, 2, 45])

In [46]:
zx

array([12, 34,  2, 45])

In [47]:
type(zx)

numpy.ndarray

In [48]:
# dtype()

In [50]:
zx.dtype

dtype('int32')

In [72]:
zx = np.array(["car", "bus", "train", "plain", "hey", "helo", "ooooo", "gooo"])

In [73]:
zx

array(['car', 'bus', 'train', 'plain', 'hey', 'helo', 'ooooo', 'gooo'],
      dtype='<U5')

In [74]:
zx.dtype

dtype('<U5')

In [54]:
zx = np.array(["car", "bus", 56, "train", "plain", 56, 100])

In [75]:
zx

array(['car', 'bus', 'train', 'plain', 'hey', 'helo', 'ooooo', 'gooo'],
      dtype='<U5')

In [76]:
zx.dtype

dtype('<U5')

In [77]:
help(np.array_split)

Help on _ArrayFunctionDispatcher in module numpy:

array_split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.

    Please refer to the ``split`` documentation.  The only difference
    between these functions is that ``array_split`` allows
    `indices_or_sections` to be an integer that does *not* equally
    divide the axis. For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.

    See Also
    --------
    split : Split array into multiple sub-arrays of equal size.

    Examples
    --------
    >>> x = np.arange(8.0)
    >>> np.array_split(x, 3)
    [array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.])]

    >>> x = np.arange(9)
    >>> np.array_split(x, 4)
    [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]



In [78]:
zx = np.array(["car", "bus", 56, "train", "plain", 56, 100])

In [79]:
np.array_split(zx, 3)

[array(['car', 'bus', '56'], dtype='<U11'),
 array(['train', 'plain'], dtype='<U11'),
 array(['56', '100'], dtype='<U11')]