In [1]:
print("hello world")

hello world


In [2]:
print("gooo")

gooo


# Start Numpy

In [ ]:
# Numpy : numarical Python

In [ ]:
# list
# tuple
# set
# dictiorny

In [ ]:
# array = ====>   list

In [ ]:
list => hitrogenious:

# lst = [12, "hlo", "car", 100, True]

In [ ]:
numpy ==> 2005 
trevious oliphent

In [ ]:
Numpy   ====> 50x
[10, 10, 34, 10, 1000, 34, 45]

python 70%
c/c#   30%

List

In [ ]:
# numpy

In [3]:
!pip install numpy

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [6]:
import numpy as np

### ndarray : when we create an object with the help of array method. that object is called ndarray.

In [10]:
ar = np.array(120)

In [11]:
a = 10
type(a)

int

In [12]:
type(ar)

numpy.ndarray

### ndim attribute

In [ ]:
help to check the demesion of an ndarray --- array

In [13]:
ar.ndim

0

In [14]:
xyz = np.array([12, 10, 43, 23, 100])

In [15]:
xyz

array([ 12,  10,  43,  23, 100])

In [16]:
xyz.ndim

1

In [20]:
arr = np.array([[12, 34, 23, 56, 12, 100], [45, 234, 12, 34, 23, 1,]])

In [21]:
arr

array([[ 12,  34,  23,  56,  12, 100],
       [ 45, 234,  12,  34,  23,   1]])

In [22]:
arr.ndim

2

In [25]:
x = np.array([[12, 345, 23, 1], [45, 67, 34, 23], [56, 34, 23, 45]])

In [26]:
x

array([[ 12, 345,  23,   1],
       [ 45,  67,  34,  23],
       [ 56,  34,  23,  45]])

In [27]:
x.ndim

2

In [35]:
zx = np.array([[[12, 45, 3, 10], [45, 34, 56, 3]], [[45, 34, 23, 12], [45, 23, 12, 100]]])

In [36]:
zx

array([[[ 12,  45,   3,  10],
        [ 45,  34,  56,   3]],

       [[ 45,  34,  23,  12],
        [ 45,  23,  12, 100]]])

In [37]:
zx.ndim

3

In [38]:
# ndarrays : 

In [44]:
x = np.array([[12, 5, 10], [34, 5, 12]])

In [45]:
x.ndim

2

### shape : return # number of rows and columns in an ndarray.

In [46]:
x = np.array([[12, 5, 10], [34, 5, 12]])

In [47]:
x

array([[12,  5, 10],
       [34,  5, 12]])

In [48]:
x.ndim

2

In [49]:
x.shape

(2, 3)

In [50]:
xyz = np.array([12, 10, 43, 23, 100])

In [53]:
xyz.shape

(5,)

In [54]:
zx = np.array([[[12, 45, 3, 10], [45, 34, 56, 3]], [[45, 34, 23, 12], [45, 23, 12, 100]]])

In [55]:
zx

array([[[ 12,  45,   3,  10],
        [ 45,  34,  56,   3]],

       [[ 45,  34,  23,  12],
        [ 45,  23,  12, 100]]])

In [56]:
zx.shape

(2, 2, 4)

In [57]:
d = np.array([[[[[12]]]]])

In [58]:
d

array([[[[[12]]]]])

In [59]:
d.ndim

5

In [ ]:
# list:

# numpy