In [1]:
# Numpy:


## joining two numpy ndarrays

In [2]:
import numpy as np

In [3]:
x = np.array([12, 45, 34, 10])

In [4]:
y = np.array([45, 34, 23, 12])

In [5]:
z = x + y

In [6]:
z

array([57, 79, 57, 22])

In [7]:
print("xyz" + "abc")

xyzabc


In [ ]:
# concatenation, vstack, hstack

In [9]:
zx = np.concatenate((x, y))

In [10]:
zx

array([12, 45, 34, 10, 45, 34, 23, 12])

In [11]:
# vstack:

In [22]:
qw = np.vstack((x, y))

In [23]:
qw

array([[12, 45, 34, 10],
       [45, 34, 23, 12]])

In [24]:
# list : mutable

In [25]:
arr = np.array([12, 45, 34, 23, 67, 45, 34, 100, 101, 67, 100])

In [26]:
arr.ndim

1

In [27]:
arr[4] = 87

In [28]:
arr

array([ 12,  45,  34,  23,  87,  45,  34, 100, 101,  67, 100])

In [29]:
arr[-2] = 87

In [30]:
arr

array([ 12,  45,  34,  23,  87,  45,  34, 100, 101,  87, 100])

In [31]:
# append()

In [32]:
arr

array([ 12,  45,  34,  23,  87,  45,  34, 100, 101,  87, 100])

In [33]:
xyz = np.append(arr, 1000)

In [34]:
xyz

array([  12,   45,   34,   23,   87,   45,   34,  100,  101,   87,  100,
       1000])

### insert()

In [35]:
xy = np.array([12, 34, 23, 56, 78, 345])

In [36]:
qw = np.insert(xy, 2, 130)

In [37]:
qw

array([ 12,  34, 130,  23,  56,  78, 345])

In [38]:
xy = np.array([12, 34, 23, 56, 78, 345])

In [39]:
xy

array([ 12,  34,  23,  56,  78, 345])

In [40]:
tk = np.insert(xy, [1, 3, 5], [100, 400, 600])

In [41]:
tk

array([ 12, 100,  34,  23, 400,  56,  78, 600, 345])

In [42]:
# delete

In [43]:
xy = np.array([12, 34, 23, 56, 78, 345])

In [47]:
np.delete(xy, [3, 5])

array([12, 34, 23, 78])

In [49]:
xy = np.array([12, 34, 23, 56, 78, 345])
zx = np.array([45, 67, 45, 34, 23, 12])

In [53]:
np.stack((xy, zx), axis = 1)

array([[ 12,  45],
       [ 34,  67],
       [ 23,  45],
       [ 56,  34],
       [ 78,  23],
       [345,  12]])

## reshape()

## 1d to 2d

In [62]:
zx = np.array([12, 34, 45, 34, 56, 3, 78, 100, 45])

In [63]:
len(zx)

9

In [64]:
zx.ndim

1

In [66]:
yu = zx.reshape(3, 3)

In [67]:
yu

array([[ 12,  34,  45],
       [ 34,  56,   3],
       [ 78, 100,  45]])

In [68]:
yu.ndim

2

In [69]:
# -1

In [70]:
zx = np.array([12, 34, 45, 34, 56, 3, 78, 100, 45])

In [71]:
zx

array([ 12,  34,  45,  34,  56,   3,  78, 100,  45])

In [72]:
zx.reshape(3, -1)

array([[ 12,  34,  45],
       [ 34,  56,   3],
       [ 78, 100,  45]])

In [73]:
zx = np.array([12, 34, 45, 34, 56, 3, 78, 100])

In [75]:
zx.reshape(4, -1)

array([[ 12,  34],
       [ 45,  34],
       [ 56,   3],
       [ 78, 100]])

In [76]:
zx = np.array([12, 34, 45, 34, 56, 3, 78, 100])

In [79]:
zx.reshape(-1, 2)

array([[ 12,  34],
       [ 45,  34],
       [ 56,   3],
       [ 78, 100]])

In [80]:
# 2d -----> 1d

In [81]:
zx = np.array([[23, 45, 34, 23, 100], [56, 7, 34, 23, 12]])

In [82]:
zx

array([[ 23,  45,  34,  23, 100],
       [ 56,   7,  34,  23,  12]])

In [83]:
zx.ndim

2

In [85]:
zx.reshape(10)

array([ 23,  45,  34,  23, 100,  56,   7,  34,  23,  12])

In [86]:
zx = np.array([[23, 45, 34, 23, 100], [56, 7, 34, 23, 12]])

In [87]:
zx.reshape(-1)

array([ 23,  45,  34,  23, 100,  56,   7,  34,  23,  12])

In [88]:
# 1d =------> 3d

In [89]:
qw = np.array([12, 34, 45, 34, 56, 3, 78, 100, 56, 34, 23, 100])

In [90]:
len(qw)

12

In [95]:
qw.reshape(3, 2, -1)

array([[[ 12,  34],
        [ 45,  34]],

       [[ 56,   3],
        [ 78, 100]],

       [[ 56,  34],
        [ 23, 100]]])

In [96]:
#3d to 1d

In [98]:
x = np.array([[[ 12,  34],
        [ 45,  34]],

       [[ 56,   3],
        [ 78, 100]],

       [[ 56,  34],
        [ 23, 100]]])

In [99]:
x.ndim

3

In [100]:
x.reshape(-1)

array([ 12,  34,  45,  34,  56,   3,  78, 100,  56,  34,  23, 100])

In [ ]:
["2 x 1 = 2", "2 x 2 = 4", "2 x 3 = 6" , >>...>....>>>>>, "2 x 10 = 20"]

In [ ]:
# zx = np.array([10, 56, 4, 100, 78, 0, 2, 3, 4, 0, 34, 0])

In [ ]:
[0, 00, 000, 0000, 00000, 0000, 000, 00, 0]

In [111]:
zx = np.array([[23, 45, 2, 56], [34, 56, 340, 23]])

In [114]:
zx

array([[ 23,  45,   2,  56],
       [ 34,  56, 340,  23]])

In [112]:
np.max(zx)

340

In [113]:
np.argmax(zx)

6

In [110]:
help(np.argmax)

Help on _ArrayFunctionDispatcher in module numpy:

argmax(a, axis=None, out=None, *, keepdims=<no value>)
    Returns the indices of the maximum values along an axis.

    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will broadcast correctly against the array.

        .. versionadded:: 1.22.0

    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed. If `keepdims` is set to True,
       