In [1]:
# Simple Linear Regression.

In [43]:
class myLRAlgo:

    def __init__(self):
        self.m = None
        self.b = None

    def fit(self, x_train, y_train):
        num = 0
        dem = 0

        for i in range(x_train.shape[0]):

            num = num + ((y_train[i] - y_train.mean()) * (x_train[i] - x_train.mean()))
                # 3.51 - 6.3453 * 8.31 - 6.0
            dem = dem + ((x_train[i] - x_train.mean()) * (x_train[i] - x_train.mean()))

            self.m = num / dem
            self.b = y_train.mean() - self.m * x_train.mean()

        print("The solpe of value os m is : ", self.m)
        print("the intersept or value of b is : ", self.b)

    def predict(self, y_test):
        print("i am predicting....")
        y = self.m * y_test - self.b
        print("prediction is : " , y)

In [28]:
x_train

array([8.31, 7.42, 5.99, 6.35, 6.6 , 6.12, 5.09, 8.15, 7.21, 8.94, 5.1 ,
       5.79, 6.22, 5.12, 6.19, 5.9 , 7.35, 5.89, 9.31, 8.21, 7.73, 5.95,
       7.89, 6.75, 7.66, 6.85, 5.66, 8.99, 7.87, 8.18, 7.39, 5.42, 6.59,
       6.86, 6.17, 7.19, 7.69, 7.43, 8.22, 6.97, 6.07, 7.48, 8.35, 7.76,
       6.93, 6.3 , 6.93, 5.23, 7.36, 7.4 , 7.9 , 6.78, 6.1 , 8.09, 5.53,
       7.95, 7.04, 7.09, 7.91, 6.29, 6.51, 8.6 , 9.06, 5.84, 5.61, 8.31,
       5.48, 7.29, 6.5 , 6.61, 7.88, 5.64, 7.11, 6.94, 6.87, 7.28, 5.12,
       6.98, 7.91, 6.05, 6.07, 7.05, 4.73, 5.32, 5.58, 9.26, 7.14, 8.44,
       7.3 , 6.63, 9.58, 6.92, 7.28, 6.14, 6.53, 7.89, 6.22, 5.84, 7.94,
       7.93, 9.16, 7.32, 7.57, 7.84, 6.13, 4.26, 5.98, 6.09, 7.63, 8.65,
       5.88, 6.66, 7.36, 7.11, 6.34, 8.63, 6.47, 4.57, 6.84, 8.44, 8.13,
       7.33, 9.04, 6.19, 6.93, 6.89, 7.28, 6.26, 5.84, 6.79, 8.93, 6.93,
       6.31, 8.62, 4.79, 7.37, 6.89, 5.94, 6.47, 7.08, 7.14, 6.73, 6.1 ,
       5.11, 7.12, 7.78, 8.37, 6.94, 6.96, 8.11, 6.

In [29]:
y_train

array([3.51, 3.67, 2.84, 2.73, 1.94, 2.76, 1.86, 3.63, 3.24, 3.65, 2.3 ,
       2.35, 2.33, 2.01, 2.48, 2.43, 3.08, 2.57, 4.37, 4.08, 3.42, 3.04,
       3.67, 2.48, 2.76, 2.93, 2.21, 4.6 , 3.58, 3.76, 2.65, 2.16, 2.21,
       3.09, 2.42, 2.4 , 3.83, 3.33, 3.89, 3.28, 2.26, 2.83, 4.21, 3.54,
       2.51, 2.73, 2.89, 1.73, 3.26, 2.88, 4.  , 3.11, 2.2 , 3.55, 2.55,
       4.14, 3.5 , 3.64, 3.15, 3.23, 2.89, 3.98, 3.82, 2.18, 2.19, 3.42,
       1.61, 3.12, 3.02, 2.6 , 3.14, 2.1 , 2.66, 3.15, 2.87, 3.48, 1.98,
       3.09, 3.89, 2.58, 2.46, 3.  , 1.48, 1.86, 2.17, 3.79, 3.13, 4.03,
       3.33, 2.79, 4.43, 3.09, 2.72, 2.3 , 2.71, 2.99, 2.87, 3.26, 3.99,
       3.34, 4.25, 2.99, 3.4 , 3.47, 2.19, 1.53, 2.84, 2.31, 3.44, 3.52,
       2.08, 2.82, 2.92, 2.61, 2.09, 4.09, 2.7 , 1.94, 2.35, 3.49, 3.6 ,
       3.16, 3.33, 2.72, 2.46, 2.7 , 3.65, 2.44, 2.74, 3.08, 3.91, 3.04,
       3.18, 4.36, 1.48, 3.08, 3.26, 2.24, 2.61, 2.85, 3.03, 2.6 , 2.6 ,
       1.63, 2.99, 3.62, 4.11, 2.98, 3.08, 4.06, 3.

In [3]:
import numpy as np
import pandas as pd

In [5]:
data = pd.read_csv("my_placment_data.csv")

In [6]:
data.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [8]:
!pip install scikit-learn

     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.4 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.4 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.4 kB 217.9 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.4 kB 195.7 kB/s eta 0:00:01
     -------------------------------------- 60.4/60.4 kB 246.1 kB/s eta 0:00:00
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB 1.3 MB/s eta 0:00:09
   ---------------------------------------- 0.1/10.6 MB 812.7 kB/s eta 0:00:13
   ---------------------------------------- 0.1/10.6 MB 751.6 kB/s eta 0:00:14
    -------------------

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [9]:
from sklearn.model_selection import train_test_split

In [10]:
data

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [13]:
x = data.iloc[:, 0].values

In [14]:
x

array([6.89, 5.12, 7.82, 7.42, 6.94, 7.89, 6.73, 6.75, 6.09, 8.31, 5.32,
       6.61, 8.94, 6.93, 7.73, 7.25, 6.84, 5.38, 6.94, 7.48, 7.28, 6.85,
       6.14, 6.19, 6.53, 7.28, 8.31, 5.42, 5.94, 7.15, 7.36, 8.1 , 6.96,
       6.35, 7.34, 6.87, 5.99, 5.9 , 8.62, 7.43, 9.38, 6.89, 5.95, 7.66,
       5.09, 7.87, 6.07, 5.84, 8.63, 8.87, 9.58, 9.26, 8.37, 6.47, 6.86,
       8.2 , 5.84, 6.6 , 6.92, 7.56, 5.61, 5.48, 6.34, 9.16, 7.36, 7.6 ,
       5.11, 6.51, 7.56, 7.3 , 5.79, 7.47, 7.78, 8.44, 6.85, 6.97, 6.94,
       8.99, 6.59, 7.18, 7.63, 6.1 , 5.58, 8.44, 4.26, 4.79, 7.61, 8.09,
       4.73, 6.42, 7.11, 6.22, 7.9 , 6.79, 5.83, 6.63, 7.11, 5.98, 7.69,
       6.61, 7.95, 6.71, 5.13, 7.05, 7.62, 6.66, 6.13, 6.33, 7.76, 7.77,
       8.18, 5.42, 8.58, 6.94, 5.84, 8.35, 9.04, 7.12, 7.4 , 7.39, 5.23,
       6.5 , 5.12, 5.1 , 6.06, 7.33, 5.91, 6.78, 7.93, 7.29, 6.68, 6.37,
       5.84, 6.05, 7.2 , 6.1 , 5.64, 7.14, 7.91, 7.19, 7.91, 6.76, 6.93,
       4.85, 6.17, 5.84, 6.07, 5.66, 7.57, 8.28, 6.

In [15]:
y = data.iloc[:, 1].values

In [16]:
y

array([3.26, 1.98, 3.25, 3.67, 3.57, 2.99, 2.6 , 2.48, 2.31, 3.51, 1.86,
       2.6 , 3.65, 2.89, 3.42, 3.23, 2.35, 2.09, 2.98, 2.83, 3.16, 2.93,
       2.3 , 2.48, 2.71, 3.65, 3.42, 2.16, 2.24, 3.49, 3.26, 3.89, 3.08,
       2.73, 3.42, 2.87, 2.84, 2.43, 4.36, 3.33, 4.02, 2.7 , 2.54, 2.76,
       1.86, 3.58, 2.26, 3.26, 4.09, 4.62, 4.43, 3.79, 4.11, 2.61, 3.09,
       3.39, 2.74, 1.94, 3.09, 3.31, 2.19, 1.61, 2.09, 4.25, 2.92, 3.81,
       1.63, 2.89, 2.99, 2.94, 2.35, 3.34, 3.62, 4.03, 3.44, 3.28, 3.15,
       4.6 , 2.21, 3.  , 3.44, 2.2 , 2.17, 3.49, 1.53, 1.48, 2.77, 3.55,
       1.48, 2.72, 2.66, 2.14, 4.  , 3.08, 2.42, 2.79, 2.61, 2.84, 3.83,
       3.24, 4.14, 3.52, 1.37, 3.  , 3.74, 2.82, 2.19, 2.59, 3.54, 4.06,
       3.76, 2.25, 4.1 , 2.37, 1.87, 4.21, 3.33, 2.99, 2.88, 2.65, 1.73,
       3.02, 2.01, 2.3 , 2.31, 3.16, 2.6 , 3.11, 3.34, 3.12, 2.49, 2.01,
       2.48, 2.58, 2.83, 2.6 , 2.1 , 3.13, 3.89, 2.4 , 3.15, 3.18, 3.04,
       1.54, 2.42, 2.18, 2.46, 2.21, 3.4 , 3.67, 2.

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [18]:
x_train.shape

(160,)

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   cgpa     200 non-null    float64
 1   package  200 non-null    float64
dtypes: float64(2)
memory usage: 3.3 KB


In [24]:
x_train.shape[0]

160

In [26]:
# for i in range(10):
#     print(i)

In [31]:
# x = 0

# for i in range(1, 10):
#     x = x + i

# print(x)

In [44]:
lr = myLRAlgo()

In [37]:
lr.predict("as")

i am predicting....


In [45]:
lr.fit(x_train, y_train)

The solpe of value os m is :  0.5502027747745323
the intersept or value of b is :  -0.8516636550118148


In [46]:
lr.predict(3.6)

i am predicting....
prediction is :  2.832393644200131


In [47]:
lr.predict(5.3)

i am predicting....
prediction is :  3.767738361316836
