In [1]:
# Numpy : 

# ndarray:

In [3]:
import numpy as np
arr = np.array([[12, 10, 90], [34, 20, 10]])

In [5]:
arr

array([[12, 10, 90],
       [34, 20, 10]])

In [6]:
arr.ndim

2

In [7]:
# shape
arr.shape

(2, 3)

In [8]:
arr = np.array([[12, 10, 90], [34, 20, 10], [23, 10, 89]])

In [9]:
arr.ndim

2

In [10]:
arr.shape

(3, 3)

In [11]:
arr

array([[12, 10, 90],
       [34, 20, 10],
       [23, 10, 89]])

In [19]:
arr = np.array([12, 10, 90, 10, 89, 67, 100, 56, 20, 10, 10, 30])

In [20]:
arr.shape

(12,)

In [21]:
arr.reshape(2, 2, 3)

array([[[ 12,  10,  90],
        [ 10,  89,  67]],

       [[100,  56,  20],
        [ 10,  10,  30]]])

In [15]:
arr

array([ 12,  10,  90,  10,  89,  67, 100,  56,  20,  10])

In [22]:
# -1

In [31]:
arr = np.array([12, 1, 90, 56, 34, 56, 23, 1, 5, 2, 5, 7, 10, 10,27])

In [33]:
arr.reshape(-1, 3)

array([[12,  1, 90],
       [56, 34, 56],
       [23,  1,  5],
       [ 2,  5,  7],
       [10, 10, 27]])

In [34]:
arr2 = np.array([[12, 10, 89, 20], [45, 20, 20, 100]])

In [36]:
arr2

array([[ 12,  10,  89,  20],
       [ 45,  20,  20, 100]])

In [39]:
arr2.reshape(-1)

array([ 12,  10,  89,  20,  45,  20,  20, 100])

In [42]:
arr2.reshape(8)

array([ 12,  10,  89,  20,  45,  20,  20, 100])

In [43]:
a = np.array([12, 10, 89, 67])
b = np.array([45, 30, 20, 100])

In [44]:
c = a + b
c

array([ 57,  40, 109, 167])

In [45]:
# concatenate

In [51]:
zx = np.concatenate([a, b])

In [52]:
zx

array([ 12,  10,  89,  67,  45,  30,  20, 100])

In [53]:
arr = np.array([12, 23, 12, 4, 23 ,10])

In [56]:
zx = np.split(arr, 3)

In [57]:
zx

[array([12, 23]), array([12,  4]), array([23, 10])]

In [58]:
for i in zx:
    print(i)

[12 23]
[12  4]
[23 10]


In [61]:
a = np.array([12, 10, 90, 100])
b = np.array([23, 10, 9, 50])

In [62]:
# stack

In [67]:
x = np.stack((a, b), axis = 1)

In [68]:
x

array([[ 12,  23],
       [ 10,  10],
       [ 90,   9],
       [100,  50]])

In [69]:
# random

In [ ]:
1) Numpy
2) Concatenate
3) Add Ndarrays
4) Stacked
5) Split
6) Shape
7) Reshape (1-D, 2-D)