In [1]:
# Numarical Python 

In [2]:
!pip install numpy


[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

# ndarray :

In [5]:
arr = np.array(12)

In [6]:
type(arr)

numpy.ndarray

In [7]:
a = 10
type(a)

int

# ndim

In [8]:
x = np.array([12, 10, 90])

In [9]:
x.ndim

1

In [10]:
y = np.array(10)

In [11]:
y.ndim

0

In [16]:
xyz = np.array([[12, 10, 98, 78], [20, 87, 48, 90]])

In [17]:
xyz

array([[12, 10, 98, 78],
       [20, 87, 48, 90]])

In [18]:
xyz.ndim

2

In [27]:
abc = np.array([[[12, 10, 98, 78], [20, 87, 48, 90]], [[23, 20, 89, 90], [56,34,56,34]], [[34, 10, 78, 67], [34, 37, 89, 29]]])

In [29]:
abc

array([[[12, 10, 98, 78],
        [20, 87, 48, 90]],

       [[23, 20, 89, 90],
        [56, 34, 56, 34]],

       [[34, 10, 78, 67],
        [34, 37, 89, 29]]])

In [30]:
abc.ndim

3

# 4D ndarray

In [36]:
arr = np.array([[[[2, 4, 5], [4, 6, 7]], [[6, 7, 8], [6, 7, 5]]], [[[7, 4, 5], [4, 6, 5]], [[4, 6, 5], [7, 5, 4]]]])

In [37]:
arr

array([[[[2, 4, 5],
         [4, 6, 7]],

        [[6, 7, 8],
         [6, 7, 5]]],


       [[[7, 4, 5],
         [4, 6, 5]],

        [[4, 6, 5],
         [7, 5, 4]]]])

In [38]:
arr.ndim

4

In [39]:
r = np.array([[[[4]]]])

In [40]:
r.ndim

4

In [41]:
r

array([[[[4]]]])

#  indexing

In [42]:
arr = np.array([23 ,10, 30, 78, 10])

In [43]:
arr.ndim

1

In [44]:
arr[2]

30

In [45]:
arr[-2]

78

# slicing

In [ ]:
# [start : end : incremnet]
start = 0
end = n - 1
increment = 1

In [46]:
arr = np.array([34, 10, 90, 78, 67, 34, 10])

In [47]:
arr

array([34, 10, 90, 78, 67, 34, 10])

In [49]:
arr[1 : 4]

array([10, 90, 78])

In [51]:
arr[2 : ]

array([90, 78, 67, 34, 10])

In [52]:
arr[: 4]

array([34, 10, 90, 78])

In [54]:
arr[: : 2]

array([34, 90, 67, 10])

In [55]:
arr

array([34, 10, 90, 78, 67, 34, 10])

In [56]:
arr[: : -1]

array([10, 34, 67, 78, 90, 10, 34])

In [57]:
arr = np.array([34, 10, 90, 78, 67, 34, 10])

In [58]:
arr.sort()

In [59]:
arr

array([10, 10, 34, 34, 67, 78, 90])

In [ ]:
where()

In [60]:
arr = np.array([34, 10, 90, 78, 67, 34, 10])

In [67]:
np.where(arr == 10)

(array([1, 6], dtype=int64),)

In [65]:
help(np.where)

Help on _ArrayFunctionDispatcher in module numpy:

where(...)
    where(condition, [x, y], /)

    Return elements chosen from `x` or `y` depending on `condition`.

    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.

    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.

    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.

    See Also
    --------
    choose
    nonzero : The function that is called when x and y are om

In [70]:
arr2 = np.array([[23, 10, 89, 67, 10], [45, 30, 89, 90, 18]])

In [71]:
arr2

array([[23, 10, 89, 67, 10],
       [45, 30, 89, 90, 18]])

In [74]:
arr2[1][3]

90

In [76]:
arr2[0][2]

89

In [77]:
arr2[1][0]

45

In [83]:
arr2 = np.array([[23, 10, 89, 67, 10], [45, 30, 89, 90, 18]])

In [81]:
arr2[1][2 :]

array([89, 90, 18])

In [82]:
arr2[0][1 : 4]

array([10, 89, 67])

In [84]:
arr2 = np.array([[[23, 10, 89, 67, 10], [45, 30, 89, 90, 18]], [[34, 30, 89, 20, 90], [45, 9, 98, 90, 23]]])

In [88]:
arr2[1][1][1]

9

In [ ]:
topics done:
1) ndarry
2) Where method
3) ndim attribute
4) Indexing
5) slicing
6) sort method
7) creating 1-D, 2-D, 3-D, 4-D ndarrays
