In [1]:
# Numpy

In [2]:
# random : /

In [3]:
from numpy import random

In [11]:
x = random.randint(100)

In [12]:
x

78

In [17]:
y = random.rand()

# 0 to 1

In [18]:
y

0.0012741811430339034

In [30]:
zx = random.randint(100, size = (2, 10))

In [29]:
zx

array([[[43, 33, 74, 15, 60, 97, 45,  5, 26, 13],
        [29, 94, 89, 52, 34, 85, 71, 60, 35, 74],
        [ 1, 62, 30, 30,  7, 94, 13, 76, 23, 97]],

       [[13, 64, 20, 46,  8, 74,  6,  5, 80, 14],
        [80, 26, 90, 19, 86, 37, 91, 19, 56,  2],
        [89, 21, 38, 59,  8, 76, 41, 39, 75, 81]]])

In [55]:
zx = random.choice([10, 20, 89, 67, 34, 100], size = (3, 10), p=[0.1, 0.3, 0.1, 0.0, 0.3, 0.2])

In [56]:
zx

array([[ 20,  10,  89,  20,  34,  34,  34,  10,  34,  20],
       [ 89,  10,  34,  10,  34,  10,  89,  20, 100, 100],
       [ 34,  10,  34, 100, 100, 100, 100,  10,  20,  20]])

In [57]:
import numpy as np

In [62]:
arr = np.array([12, 10, 20, 78, 58, 100, 45])

In [63]:
arr

array([ 12,  10,  20,  78,  58, 100,  45])

In [64]:
random.shuffle(arr)

In [65]:
arr

array([ 58,  12,  20,  78,  10,  45, 100])

In [72]:
zx = random.poisson(lam = 2, size = (10))

In [73]:
zx

array([2, 3, 2, 1, 1, 1, 3, 3, 4, 4])

In [75]:
help(random.poisson)

Help on built-in function poisson:

poisson(...) method of numpy.random.mtrand.RandomState instance
    poisson(lam=1.0, size=None)
    
    Draw samples from a Poisson distribution.
    
    The Poisson distribution is the limit of the binomial distribution
    for large N.
    
    .. note::
        New code should use the `~numpy.random.Generator.poisson`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    lam : float or array_like of floats
        Expected number of events occurring in a fixed-time interval,
        must be >= 0. A sequence must be broadcastable over the requested
        size.
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  If size is ``None`` (default),
        a single value is returned if ``lam`` is a scalar. Otherwise,
        ``np.array(lam).size`` samp

In [76]:
topics done:
1) Random
2) randint
3) rand
4) choice
5) shuffle
6) gerrating random data using randint, rand or choice, 1-D, 2-D, 3-D

SyntaxError: invalid syntax (560393209.py, line 1)