In [1]:
import numpy as np

In [4]:
x = np.array([[23, 45], [56, 34], [34, 23], [56, 78], [56, 34]])

In [5]:
x

array([[23, 45],
       [56, 34],
       [34, 23],
       [56, 78],
       [56, 34]])

In [7]:
y = np.array([0, 1, 0, 0, 1])

In [8]:
y

array([0, 1, 0, 0, 1])

In [11]:
x[y == 0]

array([[23, 45],
       [34, 23],
       [56, 78]])

In [12]:
# mean()

In [15]:
x[y == 0].mean(axis = 0)

array([37.66666667, 48.66666667])

In [16]:
y = np.array([0, 1, 0, 0, 1])

In [17]:
np.unique(y)

array([0, 1])

In [18]:
zx = np.array([12, 34])


In [27]:
ab = np.array([12, 10])

In [28]:
if (zx == ab).all():
    print("they are same")

In [ ]:
for i in range(1, 11):
    print(i)
    if i == 5:
        print